name: Test with Conda, Py3.7 to 3.10

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install conda and dependencies
      run: |
        conda install numpy pip setuptools pyparsing pytest pytest-cov coverage
        conda update -n base -c defaults conda
        conda install -y -c conda-forge epics-base
        conda install -y -c lcls-ii procserv
        conda info
        conda list
    - name: Install pyepics
      run: |
        python -m pip install --upgrade pip
        python setup.py install
    - name: Run test suite
      run: |
        python -m pip install psutil
        cd tests
        sh run_tests.sh
